openapiOptions:
  file:
    - file: v1alpha/core.proto
      option:
        info:
          title: CIAM Authz
          description: This is the CIAM-Authz service based on the OpenAPI 2.0 specification.
          contact:
            email: ciam-authz@redhat.com
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html
        tags:
            - name: AuthZ
              description: Everything about your AuthZ
              externalDocs:
                description: CIAM AuthZ 
                url: http://<TODO>
            - name: user
              description: Operations about user  
        schemes:
          - HTTP
          - HTTPS
        consumes:
          - application/json
        produces:
          - application/json
        responses:
          "401":
            description: Returned when no valid identity information provided to a protected endpoint.
            schema: {}
          "403":
            description: Returned when the user does not have permission to access the resource.
            schema: {}
          "500":
            description: Returned when an unexpected error occurs during request processing.
            schema: {}
  method:
    - method: api.v1alpha.CheckPermission.CheckPermission
      option:
        summary: Checks the permission and returns allowed (true) or not allowed (false)
        description: CheckPermission endpoint is used by the clients to determine if the given "subject" has the given permission "Operation" on a given "Resource"
        responses:
          "200":
            examples:
              "application/json": '{"result": true, "description": ""}'
    - method: api.v1alpha.LicenseService.ModifySeats
      option:
        summary: Assign or unassign users to/from the license.
        description: >
          Assign or unassign users to or from the license. 
          Users assigned may access the service identified by serviceId
          as contracted with an organization (identified by orgId).
          Assigned users consume a limited number of seats in a license.
    - method: api.v1alpha.LicenseService.GetSeats
      option:
        summary: Gets user details with filters.
        description: Get details of users who are assigned to the license or available to be assigned.
    - method: api.v1alpha.LicenseService.GetLicense
      option:
        summary: Summarize a license.
        description: > 
          Returns information about the license, 
          including the number of entitled seats (maximum assignable)
          and the current number of available seats.
    - method: api.v1alpha.LicenseService.EntitleOrg
      option:
        summary: Entitle an Org access through a seat based license for a service.
        description: >
          Grants a given Org a seat based license to a given service. A maximum number of entitled seats
          
