openapiOptions:
  file:
    - file: v1alpha/core.proto
      option:
        info:
          title: CIAM Authz
          description: This is the CIAM-AuthZ service based on the OpenAPI 2.0 specification.
          contact:
            email: ciam-authz@redhat.com
          license:
            name: Apache 2.0
            url: http://www.apache.org/licenses/LICENSE-2.0.html
          version: 1.0.11
        tags:
            - name: AuthZ
              description: Everything about your AuthZ
              externalDocs:
                description: CIAM AuthZ 
                url: http://<TODO>
            - name: user
              description: Operations about user  
        schemes:
          - HTTP
          - HTTPS
        consumes:
          - application/json
        produces:
          - application/json
        responses:
          "401":
            description: Returned when no valid identity information provided to a protected endpoint.
            schema: {}
          "403":
            description: Returned when the user does not have permission to access the resource.
            schema: {}
          "500":
            description: Returned when an unexpected error occurs during request processing.
            schema: {}
  method:
    - method: api.v1alpha.CheckPermission.CheckPermission
      option:
        summary: Checks the permission and returns allowed (true) or not allowed (false)
        description: CheckPermission endpoint is used by the clients to determine if the given "subject" has the given permission "Operation" on a given "Resource"
        responses:
          "200":
            examples:
              "application/json": '{"result": true, "description": ""}'
    - method: api.v1alpha.SeatsService.CreateSeats
      option:
        summary: Add licenses to users
        description: Adds users to seats/licenses until the seats of the bought license are full.
    - method: api.v1alpha.SeatsService.DeleteSeats
      option:
        summary: Removes licenses from users
        description: Removes users from seats/licenses
    - method: api.v1alpha.SeatsService.GetSeats
      option:
        summary: Gets licensed/unlicensed users and count.
        description: Removes users from seats/licenses