app:
  server:
    kind: "grpc"
    port: "50051"
    grpc-web-httpPort: "8080" # only needed for grpc kind
    grpc-web-httpsPort: "8443" # only needed for grpc kind (for now)
  accessRepository:
    kind: "stub"
    endpoint: "http://localhost:50052" # spiceDB Endpoint
    token: "foobar" # spiceDB token
