#This workflow file builds, tests and pushes the image to quay.
#v0.0.1
#To be modularized later.
name: Build, Test, Push Image
on:
  push:
    branches:
      - 'main'

concurrency:
  # Only run workflow for latest push, cancel in progress runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test ./...
  push-to-registry:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }} #TODO
          password: ${{ secrets.QUAY_TOKEN }} #TODO
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: quay.io/dguhr/test:latest #TODO
